In [12]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv(r"C:\Users\ashwi\Desktop\machine_learning\Instagram_Analytics.csv")

In [3]:
df.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low

In [4]:
df.shape

(29999, 23)

In [5]:
df.describe()

,account_id,follower_count,has_call_to_action,post_hour,likes,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count
count,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000
mean,10.567819,10278.305477,0.348778,11.499417,287.653588,8.521917,14.426614,42.517284,6272.475449,8466.952498,0.042107,502.152805,120.081169,7.987933
std,5.763952,6691.862669,0.476592,6.900587,317.647682,10.116505,16.420899,47.808844,4985.877059,6825.900355,0.024095,290.364038,11.009108,2.828130
min,1.000000,3083.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,268.000000,327.000000,0.000000,0.000000,70.000000,0.000000
25%,6.000000,5824.000000,0.000000,6.000000,104.000000,3.000000,5.000000,15.000000,3058.000000,4102.000000,0.024000,251.000000,113.000000,6.000000
50%,11.000000,9044.000000,0.000000,12.000000,199.000000,6.000000,10.000000,29.000000,4913.000000,6595.000000,0.040600,501.000000,120.000000,8.000000
75%,16.000000,10739.000000,1.000000,17.000000,363.000000,11.000000,19.000000,54.000000,7863.000000,10620.500000,0.057000,755.000000,127.000000,10.000000
max,20.000000,31095.000000,1.000000,23.000000,10632.000000,339.000000,516.000000,1542.000000,73339.000000,105203.000000,0.271000,1000.000000,166.000000,21.000000

In [9]:
df.columns

Index(['post_id', 'account_id', 'account_type', 'follower_count', 'media_type',
       'content_category', 'traffic_source', 'has_call_to_action',
       'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes',
       'comments', 'shares', 'saves', 'reach', 'impressions',
       'engagement_rate', 'followers_gained', 'caption_length',
       'hashtags_count', 'performance_bucket_label'],
      dtype='str')

In [10]:
df.drop(columns=['post_id','account_id','post_datetime','post_date'])

,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_hour,day_of_week,likes,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,brand,3551,reel,Technology,Home Feed,1,6,Saturday,194,5,7,34,4327,6230,0.0385,899,100,7,medium
1,creator,31095,image,Fitness,Hashtags,1,15,Friday,449,10,21,68,7451,8268,0.0663,805,122,5,viral
2,brand,8167,reel,Beauty,Reels Feed,0,16,Thursday,114,2,1,22,1639,2616,0.0531,758,115,8,high
3,creator,9044,carousel,Music,External,0,3,Thursday,91,0,7,0,2877,3171,0.0309,402,115,7,medium
4,creator,15986,reel,Technology,Profile,0,9,Friday,154,8,5,21,5350,8503,0.0221,155,112,9,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,brand,10739,carousel,Travel,Reels Feed,0,10,Wednesday,0,1,2,5,1564,2493,0.0032,124,127,8,low
29995,brand,10018,image,Beauty,Hashtags,0,15,Monday,42,2,1,7,2042,2492,0.0209,310,114,12,low
29996,creator,7486,image,Photography,Explore,1,10,Monday,335,10,16,59,5887,7528,0.0558,223,115,4,high
29997,creator,10034,carousel,Technology,Explore,1,19,Saturday,188,3,0,19,5372,6312,0.0333,978,124,4,medium
29998,creator,6916,image,Technology,Explore,1,20,Tuesday,50,1,1,5,4019,5678,0.0100,272,126,11,low

In [19]:
cats_col=['account_type','media_type','content_category','traffic_source','day_of_week','performance_bucket_label']

In [13]:
le=LabelEncoder()
for col in cats_col:
    df[col]=le.fit_transform(df[col])
X=df.drop(columns=['engagement_rate', 'performance_bucket_label'])
y=df['engagement_rate']

In [15]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [22]:
model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6
)

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:post_id: str, post_datetime: str, post_date: str, day_of_week: str